### PR TITLE
Ability to extend middleware through frappe hooks

### PR DESCRIPTION
**Pull request by e-lobo**
Changes:

1. New hook introduced ✅ 
    => graphql_middlewares
   
2. Docs ✅

### CODE REVIEW

**Review by fahimalizain — APPROVED** [review]
👍🏼 👍🏼 
should we name it simply `graphql_middlewares` ? 😄

**Comment by assemmarwan** [comment]
Should we add more documentation on how to create a middleware? Including what are its parameters and what it should return

**Comment by e-lobo** [comment]
> Should we add more documentation on how to create a middleware? Including what are its parameters and what it should return

added 👍

**Review by Abadulrehman — APPROVED** [review]
:100:

**Review by assemmarwan — APPROVED** [review]

**Pull request merged**
